# Generated by Django 5.2.15 on 2026-07-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('ASSIGN_ROLE', 'Assign Role'), ('ASSIGN_PERMISSION', 'Assign Permission'), ('PASSWORD_CHANGE', 'Password Change'), ('PASSWORD_RESET_REQUEST', 'Password Reset Request'), ('PASSWORD_RESET', 'Password Reset')], max_length=30),
        ),
    ]
